### ISSUE TITLE
Can't build the application on iOS

### ISSUE THREAD

**Issue by nobuhiko702** [reki2000/audio-stream-flutter#11]
### Issue Description

After adding mp_audio_stream as a dependency, it seems to create a compilation conflict with the cloud_firestore plugin, resulting in the following error:
````
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running pod install... 12.6s
Running Xcode build...
Xcode build done. 20.2s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): 'grpc/support/port_platform.h' file not found
/GitHub/test/ios/Pods/gRPC-C++/src/core/lib/gpr/string.h:21:9

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
````

### Steps to Reproduce

```
flutter create test
cd test
flutter pub add mp_stream_audio
flutter pub add cloud_firestore
flutter run
```

### Expected Behavior

Build Success

### Actual Behavior

Failed to build iOS app

### Environment Information

- Operating System: macOS
- Development Environment: iOS emulator

### Additional Information

The following entries appear in the Podfile.lock, and I think this might be the cause of the problem:

```
  - "gRPC-C++ (1.50.1)":
  - "gRPC-C++/Implementation (= 1.50.1)"
  - "gRPC-C++/Interface (= 1.50.1)"
```

**Comment by nobuhiko702** [comment]
<img width="784" alt="Screenshot" src="https://github.com/reki2000/mp-audio-stream/assets/139615105/ec9d5956-3353-4c84-a5a4-1dee9f102b19">

**Comment by reki2000** [comment]
I tried following on Flutter 3.10.6, but it hangs while pod install even without mp_audio_stream. couldn't dig the problem...

```
$ flutter create test
$ cd test
$ flutter pub add cloud_firestore
$ flutter run

Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Running pod install...                                               
```

**Comment by nobuhiko702** [comment]
> I tried following on Flutter 3.10.6, but it hangs while pod install even without mp_audio_stream. couldn't dig the problem...
> 
> ```
> $ flutter create test
> $ cd test
> $ flutter pub add cloud_firestore
> $ flutter run
> 
> Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
> Running pod install...                                               
> ```

Pod installing, need a little more waiting 🤣 (probably)

**Comment by nialljawad96** [comment]
Was this ever solved? I'm having the same sad issue @nobuhiko702
