### ISSUE TITLE
Does not work on MacOS.

### ISSUE THREAD

**Issue by nialljawad96** [reki2000/audio-stream-flutter#18]
This package does not work on MacOS.

Steps to reproduce:
Try example App provided on MacOS. No sound is emitted. 

Grateful for your work and any help on this matter @reki2000 @hollingsworthd 

Equivalent project works on Web.
<img width="1249" alt="Screenshot 2024-04-05 at 15 04 56" src="https://github.com/reki2000/mp-audio-stream/assets/64364012/6468d9b1-9b8a-48ff-b6a0-ac3f2c30116e">

**Comment by reki2000** [comment]
thanks. reproduced on my mac. will check.
