### ISSUE TITLE
Can not build on Latest Sample code

### ISSUE THREAD

**Issue by steveshp** [reki2000/audio-stream-flutter#22]
1. error message
     /Users/stevepark/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/Users/stevepark/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/stevepark/Library/Android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -DDART_SHARED_LIB -Dmp_audio_stream_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/mp_audio_stream.dir/mp_audio_stream.cc.o -MF CMakeFiles/mp_audio_stream.dir/mp_audio_stream.cc.o.d -o CMakeFiles/mp_audio_stream.dir/mp_audio_stream.cc.o -c /Volumes/ssd/Downloads/mp-audio-stream-develop/src/mp_audio_stream.cc
  /Volumes/ssd/Downloads/mp-audio-stream-develop/src/mp_audio_stream.cc:4:10: fatal error: './miniaudio/miniaudio.h' file not found
  #include "./miniaudio/miniaudio.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      /Users/stevepark/Library/Android/sdk/cmake/3.18.1/bin/ninja \
        -C \
        /Volumes/ssd/Downloads/mp-audio-stream-develop/android/.cxx/Debug/3o4n2tp3/arm64-v8a \
        mp_audio_stream
    from /Volumes/ssd/Downloads/mp-audio-stream-develop/android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

**Comment by reki2000** [comment]
@steveshp Did you do ` git submodule init && git submodule update` after you did `git clone` ? If your `miniaudio` directory is empty, please try it.
